name: shareskill1
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3 #latest version
  font_awesome_flutter: ^10.4.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  googleapis: ^11.2.0
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  google_sign_in: ^5.4.3
  google_fonts: ^5.0.0
  expandable: ^5.0.1
  expand_widget: ^3.1.1
  animated_text_kit: ^4.2.2
  firebase_core: ^2.13.1
  list_wheel_scroll_view_nls: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  assets:
    - images/
 
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Medium.ttf
